version: '3'

services:
  qa-script:
    image: python:3.9-slim
    container_name: qa-script-container
    volumes:
      - .:/app  
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python main.py"
    ports:
      - "5000:5000"
