version: '3'

services:
  rag-demo:
    image: python:3.9-slim
    container_name: rag-demo
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
      pip install -r requirements.txt &&
      python main.py
      "
    ports:
      - "5000:5000"